### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by NHOrus** [arc-theme/arc-icon-theme#2]
There are enough changes and modifications to produce one, in my opinion.

**Comment by shoeper** [comment]
So far NicoHood maintains the arc-theme and also wanted to maintain the icon-theme if I understood correctly.

This was more like I had an issue on my personal computer with the wrong battery icon and there already were PRs that didn't get merged in the initial repository from horst3180, so I reviewed and merged them to install it on my machine.

**Comment by shoeper** [comment]
So I've basically merged these

* fix battery icon (https://github.com/horst3180/arc-icon-theme/pull/22)
* make icon rendering faster (https://github.com/horst3180/arc-icon-theme/pull/48)
* add dialog-password icons to /status (https://github.com/horst3180/arc-icon-theme/pull/46)

I currently think about - although it isn't best practise - changing master to get rid of all the minimal commits from 46 and could do a release afterwards. So far releases have only been simple tags, though. It would maybe easier to just install from master.

**Comment by NHOrus** [comment]
https://github.com/NicoHood/arc-icon-theme does not contain commits you got, so I count you as current upstream. In practical sense. Most commits and newest commits.

As Gentoo person, I want practical solutions to my icon and theme problem. Maybe coordinate with NicoHood about squished release being merged into new upstream?

**Comment by shoeper** [comment]
In case you're a user you can get the three improvements above by either cloning this repository or downloading the source as archive. And then just follow the install instructions https://github.com/arc-theme/arc-icon-theme#installation

> As Gentoo person, I want practical solutions to my icon and theme problem. Maybe coordinate with NicoHood about squished release being merged into new upstream?

Yes, when I squash it I can resubmit it. Without he didn't want to take it and for me the most important thing was to just make it work.

**Comment by NicoHood** [comment]
Hi there!
As already mentioned, me and @fossfreedom are maintaining the arc-theme and lately also the arc-icon theme to fix some bugs. I'd like to see all contributions in one place, so if you like to take over your changes to our repo please open a PR and we are happy to review merge the changes.

**Comment by shoeper** [comment]
Looks like new upstream is https://github.com/arc-design/arc-theme
